import { createClient } from '@supabase/supabase-js';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
let state={products:[],movements:[]};
const $=s=>document.querySelector(s); const product=id=>state.products.find(p=>String(p.id)===String(id)); const low=p=>p.stock<=p.minimum;
const status=p=>p.stock===0?'<span class="badge out">Sem estoque</span>':low(p)?'<span class="badge low">Estoque baixo</span>':'<span class="badge ok">Disponível</span>';
const date=v=>new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
function render(){const lows=state.products.filter(low),total=state.products.reduce((n,p)=>n+p.stock,0);$('#product-count').textContent=state.products.length;$('#stock-total').textContent=total.toLocaleString('pt-BR');$('#low-stock').textContent=lows.length;$('#low-stock-list').innerHTML=lows.length?lows.map(p=>`<div class="compact-row"><div><b>${p.name}</b><small>${p.code} · mínimo: ${p.minimum}</small></div><span class="badge low">${p.stock} un.</span></div>`).join(''):'<p class="empty">Nenhum item precisa de reposição.</p>';$('#recent-movements').innerHTML=state.movements.slice(0,5).map(m=>`<div class="compact-row"><div><b>${m.type==='entrada'?'Entrada':'Saída'} · ${product(m.productId)?.name||'Produto'}</b><small>${m.person} · ${m.date}</small></div><span class="badge ${m.type}">${m.type==='entrada'?'+':'-'}${m.quantity}</span></div>`).join('')||'<p class="empty">Sem movimentações.</p>';renderProducts();renderMovement()}
function renderProducts(){const q=$('#product-search').value.toLowerCase();$('#products-table').innerHTML=state.products.filter(p=>`${p.name} ${p.code} ${p.category}`.toLowerCase().includes(q)).map(p=>`<tr><td><b>${p.name}</b></td><td>${p.code}</td><td>${p.category}</td><td><b>${p.stock}</b><small>mínimo: ${p.minimum}</small></td><td>${status(p)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum produto encontrado.</td></tr>'}
function renderMovement(){const select=$('#movement-product'),selected=select.value;select.innerHTML=state.products.map(p=>`<option value="${p.id}">${p.name} (${p.stock} un.)</option>`).join('');select.value=selected||state.products[0]?.id;$('#movement-history').innerHTML=state.movements.map(m=>`<div class="history-item"><span class="history-icon ${m.type==='saida'?'out':''}">${m.type==='entrada'?'↓':'↑'}</span><div><b>${m.type==='entrada'?'Entrada':'Saída'} de ${m.quantity} un. — ${product(m.productId)?.name||'Produto'}</b><small>${m.person} · ${m.date}${m.note?' · '+m.note:''}</small></div></div>`).join('')||'<p class="empty">Nenhuma movimentação registrada.</p>'}
async function load(){const [a,b]=await Promise.all([supabase.from('products').select('*').order('name'),supabase.from('movements').select('*').order('created_at',{ascending:false})]);if(a.error||b.error){alert((a.error||b.error).message);return}state.products=a.data.map(p=>({...p,minimum:p.minimum_stock}));state.movements=b.data.map(m=>({id:m.id,type:m.movement_type,productId:m.product_id,quantity:m.quantity,person:m.recipient,note:m.note,date:date(m.created_at)}));render()}
function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#page-title').textContent={dashboard:'Visão geral',products:'Produtos',movement:'Movimentações'}[id];$('#header-action').textContent=id==='products'?'+ Cadastrar produto':'+ Nova movimentação'}
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));$('#header-action').onclick=()=>$('.view.active').id==='products'?$('#product-dialog').showModal():view('movement');$('#add-product').onclick=()=>$('#product-dialog').showModal();$('#product-search').oninput=renderProducts;
$('#product-form').onsubmit=async e=>{e.preventDefault();const {error}=await supabase.from('products').insert({name:$('#new-name').value,code:$('#new-code').value,category:$('#new-category').value,stock:Number($('#new-stock').value),minimum_stock:Number($('#new-minimum').value)});if(error){alert(error.message);return}e.target.reset();$('#product-dialog').close();await load();view('products')};
$('#movement-form').onsubmit=async e=>{e.preventDefault();const p=product($('#movement-product').value),q=Number($('#movement-quantity').value),type=$('#movement-type').value;if(type==='saida'&&q>p.stock){alert(`Estoque insuficiente. Disponível: ${p.stock} unidade(s).`);return}const {error}=await supabase.rpc('record_movement',{p_product_id:p.id,p_type:type,p_quantity:q,p_recipient:$('#movement-person').value,p_note:$('#movement-note').value||null});if(error){alert(error.message);return}e.target.reset();$('#movement-quantity').value=1;await load();view('dashboard')};
$('#login-form').onsubmit=async e=>{e.preventDefault();const msg=$('#login-error');msg.hidden=true;const {error}=await supabase.auth.signInWithPassword({email:$('#login-email').value,password:$('#login-password').value});if(error){msg.textContent=error.message;msg.hidden=false;return}$('#auth-gate').hidden=true;await load()};
$('#today').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});render();
const {data:{session}}=await supabase.auth.getSession();if(session)load();else $('#auth-gate').hidden=false;
